spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: marketing
    url: jdbc:mysql://192.168.3.88:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    password: marketing

logging:
  register-shutdown-hook: false
  level:
    ROOT: info
    com.baomidou: off
    org.apache.ibatis: off
    cn.com.geasy.marketing: off
    jdbc.resultsettable: info
    jdbc.sqltiming: debug
    jdbc.sqlonly: off
    jdbc.connection: off
    jdbc.audit: off
    jdbc.resultset: off