#------------------------------------------------------------------
# 阿里云测试环境配置(120.78.227.225)
# 编译命令：mvn clean package -P test
# author: Phil
#------------------------------------------------------------------

# SSL 配置
server:
  port: 8443
  ssl:
    key-store: /home/tvi/marketing/cert/tomcat/214866030780708.pfx
    key-store-password: 214866030780708
    key-store-type: PKCS12

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsco67s7eooc0j49729.mysql.rds.aliyuncs.com:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: marketing
    password: marketing#2018
