#------------------------------------------------------------------
# 本地开发环境直连阿里云RDC配置
# 编译命令：mvn clean package -P localaliyun
# author: Phil
#------------------------------------------------------------------

# SSL 配置
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsco67s7eooc0j497293o.mysql.rds.aliyuncs.com:3306/marketing?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: marketing
    password: marketing#2018
