#------------------------------------------------------------------
# 公司测试环境配置(WEB:192.168.3.81 DB:192.168.3.87)
# 编译命令：mvn clean package -P localtest
# author: Phil
#------------------------------------------------------------------

# SSL 配置
server:
  port: 8443
  ssl:
    key-store: /home/tvi/apps/marketing/cert/marketing-server.p12
    key-store-password: marketing
    key-store-type: PKCS12
    key-alias: 1

# 数据库配置
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.3.87:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: marketing
    password: marketing