#------------------------------------------------------------------
# 本地开发环境配置
# 编译命令：mvn clean package -P dev
# author: Phil
#------------------------------------------------------------------

server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.3.87:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: marketing
    password: marketing
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:h2:mem:marketing;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL
#    username: sa
#    password:
#    schema: classpath:sql/dev/schema.sql,classpath:sql/dev/add.sql
#    data: classpath:sql/dev/init_data.sql,classpath:sql/dev/test_data.sql,classpath:sql/dev/unenforced.sql
#    initialization-mode: embedded
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: false
