#------------------------------------------------------------------
# 公司测试环境配置(192.168.3.81)
# 编译命令：mvn clean package -P localtest
# author: Phil
#------------------------------------------------------------------

# SSL 配置
server:
  port: 8443
  ssl:
    key-store: /home/tvi/apps/marketing/cert/marketing-server.p12
    key-store-password: marketing
    key-store-type: PKCS12
    key-alias: 1

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://rdsco67s7eooc0j497293o.mysql.rds.aliyuncs.com:3306/marketing?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: marketing
    password: marketing#2018
#    url: jdbc:mysql://192.168.3.88:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
#    username: marketing
#    password: marketing
