spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:marketing;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL
    #url: jdbc:log4jdbc:mysql://localhost:3306/trace?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: sa
    password:
    schema: classpath:sql/dev/schema.sql
#    data: classpath:sql/dev/data.sql
    initialization-mode: embedded
  h2:
    console:
      enabled: false
      path: /h2
      settings:
        web-allow-others: false


logging:
  register-shutdown-hook: false
  level:
    ROOT: info
    com.baomidou: debug
    org.apache.ibatis: debug
    cn.com.geasy.marketing: debug