spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:log4jdbc:mysql://192.168.3.88:3306/marketing?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: 12345678